### ISSUE TITLE
Size of AAB

### ISSUE THREAD

**Issue by necron4a** [jelte/be.khepri.play.assetdelivery.addressables#8]
Hi! I first time use google asset delivery. And I have one question.
I created some builds:
1. I build .aab via standart build menu with "local build path" in all addressables group settings(without your asset). Size of aab ~450Mb.
2. I build .aab via standart build menu with "remote build path" in all addressables group settings(without your asset). Size of aab ~35Mb.
3. I build .aab via google menu with  "local build path" and added "Play Asset Delivery Schema"(Install Time) for all addressables group settings.  Size of aab ~450Mb.

I try to upload build №3 to google play console(inner testing) and take error "The App Bundle contains configurations where the installation file is larger than the size limit (150MB): ARM64_V8A." What I do wrong? When I build via google menu I must get 1 file or 2(main + packed assets)?

**Comment by jelte** [comment]
it seems you are doing everything fine.
the "error" you are getting is just a warning from the google librray (for some reason they don't check if the AAB conatins assetpacks) but because it does you can still upload it to the playstore.

You will get 1 AAB with contains all the main build and asset packs this will be larger.

2. if you build with remote build path, then asset bundles will not be included in your build, resulting in the ~35MB (main only) AAB.
